name: Rust

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: page-updater

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        sudo apt-get install pandoc
        bin/build.sh
    - name: Upload 
      uses: actions/upload-artifact@v4
      with:
        name: moddl_docs
        path: target_doc/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # personal_token: ${{ secrets.PERSONAL_TOKEN }}
        # external_repository: bolta/bolta.github.io
        publish_dir: target_doc/
        destination_dir: moddl/v0.1.0/docs/develop/
